const $=id=>document.getElementById(id);let token='',busy=false,language='en';
const TEXT={
en:{sdTransfer:'SD Transfer',status:'Status',firmware:'Firmware',sdCard:'SD card',freeSpace:'Free space',transfer:'Transfer',preparedNotice:'Use prepared TinyPhone files. Browser conversion is planned for a later phase.',mediaPackage:'Media package',packageHelp:'Upload one <code>TinyPhone-media.tar</code> from Media Studio. Its WAV files and metadata are validated together and appended to the installed playlist.',tinyPhonePackage:'TinyPhone package',uploadPackage:'Upload package',wallpapers:'Wallpapers',wallpaperHelp:'Upload an exact 320 × 240 LVGL RGB565 <code>.bin</code> file (153,612 bytes).',slot:'Slot',preparedFile:'Prepared file',replaceSlot:'Replace slot',music:'Music',musicHelp:'Upload PCM16, 22050 Hz mono or stereo WAV. Safe names use lowercase letters, numbers, and underscores.',preparedWav:'Prepared WAV',sdFilename:'SD filename',replaceExisting:'Replace existing',uploadTrack:'Upload track',playlistMetadata:'Playlist metadata',playlistHelp:'Upload a UTF-8 CSV with <code>file,title,artist</code> columns.',replacePlaylist:'Replace playlist',finish:'Finish',noChanges:'No changes in this session.',exitNoRestart:'Exit without restart',applyRestart:'Apply & Restart',connecting:'Connecting…',connected:'Connected',standalone:'Standalone',mounted:'Mounted',missing:'Missing',delete:'Delete',checking:'Checking',uploading:'Uploading…',networkError:'Network error',operationFailed:'Operation failed',choosePackage:'Choose TinyPhone-media.tar.',chooseStudioPackage:'Choose the .tar file created by TinyPhone Media Studio.',chooseBin:'Choose a prepared .bin file.',wallpaperSize:'Wallpaper must be exactly 153,612 bytes.',chooseWav:'Choose a prepared WAV.',safeName:'Use lowercase letters, numbers, underscores, and .wav.',choosePlaylist:'Choose playlist.csv.',deleteConfirm:'Delete {name} from TinyPhone?',applyConfirm:'Validate changes and restart TinyPhone?',restartNotice:'TinyPhone is restarting. Reconnect after Wi-Fi closes.',exitConfirm:'Stop Wi-Fi without restarting?',closingNotice:'Transfer mode is closing.',changes:'{count} change(s) ready to apply.',unavailable:'TinyPhone is unavailable ({error}). Connect to its Wi-Fi and open http://192.168.4.1.',state_idle:'Idle',state_starting:'Starting',state_ready:'Ready',state_uploading:'Uploading',state_applying:'Applying',state_error:'Error',state_unknown:'Unknown'},
vi:{sdTransfer:'Truyền dữ liệu SD',status:'Trạng thái',firmware:'Firmware',sdCard:'Thẻ SD',freeSpace:'Dung lượng trống',transfer:'Truyền dữ liệu',preparedNotice:'Dùng các tệp đã chuẩn bị cho TinyPhone. Chuyển đổi ngay trên trình duyệt sẽ được bổ sung sau.',mediaPackage:'Gói phương tiện',packageHelp:'Tải lên một tệp <code>TinyPhone-media.tar</code> từ Media Studio. Tệp WAV và siêu dữ liệu sẽ được kiểm tra cùng nhau rồi thêm vào danh sách nhạc.',tinyPhonePackage:'Gói TinyPhone',uploadPackage:'Tải gói lên',wallpapers:'Hình nền',wallpaperHelp:'Tải lên tệp <code>.bin</code> LVGL RGB565 đúng 320 × 240 (153.612 byte).',slot:'Vị trí',preparedFile:'Tệp đã chuẩn bị',replaceSlot:'Thay vị trí',music:'Nhạc',musicHelp:'Tải WAV PCM16, 22050 Hz mono hoặc stereo. Tên an toàn chỉ dùng chữ thường, số và dấu gạch dưới.',preparedWav:'WAV đã chuẩn bị',sdFilename:'Tên tệp trên SD',replaceExisting:'Thay tệp hiện có',uploadTrack:'Tải bài nhạc lên',playlistMetadata:'Siêu dữ liệu danh sách nhạc',playlistHelp:'Tải CSV UTF-8 có các cột <code>file,title,artist</code>.',replacePlaylist:'Thay danh sách nhạc',finish:'Hoàn tất',noChanges:'Chưa có thay đổi trong phiên này.',exitNoRestart:'Thoát không khởi động lại',applyRestart:'Áp dụng và khởi động lại',connecting:'Đang kết nối…',connected:'Đã kết nối',standalone:'Mất kết nối',mounted:'Đã gắn',missing:'Không có',delete:'Xóa',checking:'Đang kiểm tra',uploading:'Đang tải lên…',networkError:'Lỗi mạng',operationFailed:'Thao tác thất bại',choosePackage:'Hãy chọn TinyPhone-media.tar.',chooseStudioPackage:'Hãy chọn tệp .tar do TinyPhone Media Studio tạo.',chooseBin:'Hãy chọn tệp .bin đã chuẩn bị.',wallpaperSize:'Hình nền phải đúng 153.612 byte.',chooseWav:'Hãy chọn tệp WAV đã chuẩn bị.',safeName:'Chỉ dùng chữ thường, số, dấu gạch dưới và đuôi .wav.',choosePlaylist:'Hãy chọn playlist.csv.',deleteConfirm:'Xóa {name} khỏi TinyPhone?',applyConfirm:'Kiểm tra thay đổi và khởi động lại TinyPhone?',restartNotice:'TinyPhone đang khởi động lại. Hãy kết nối lại sau khi Wi-Fi tắt.',exitConfirm:'Tắt Wi-Fi mà không khởi động lại?',closingNotice:'Chế độ truyền dữ liệu đang đóng.',changes:'Có {count} thay đổi sẵn sàng áp dụng.',unavailable:'Không thể kết nối TinyPhone ({error}). Hãy kết nối Wi-Fi của máy và mở http://192.168.4.1.',state_idle:'Rảnh',state_starting:'Đang khởi động',state_ready:'Sẵn sàng',state_uploading:'Đang tải lên',state_applying:'Đang áp dụng',state_error:'Lỗi',state_unknown:'Không rõ'}};
const t=(key,values={})=>Object.entries(values).reduce((value,[name,replacement])=>value.replaceAll(`{${name}}`,replacement),TEXT[language][key]||TEXT.en[key]||key);
function applyLanguage(next){language=next==='vi'?'vi':'en';document.documentElement.lang=language;document.querySelectorAll('[data-i18n]').forEach(node=>node.textContent=t(node.dataset.i18n));document.querySelectorAll('[data-i18n-html]').forEach(node=>node.innerHTML=t(node.dataset.i18nHtml))}
const fmt=n=>{if(!Number.isFinite(Number(n)))return'—';const u=['B','KiB','MiB','GiB'];let v=Number(n),i=0;while(v>=1024&&i<u.length-1){v/=1024;i++}return`${v.toFixed(i?1:0)} ${u[i]}`};
function setBusy(value){busy=value;document.querySelectorAll('button').forEach(b=>b.disabled=value)}
function showProgress(name,loaded,total,complete=false){$('progress-card').hidden=false;$('progress-name').textContent=name;const pct=complete?100:(total?Math.min(90,Math.round(loaded*90/total)):0);$('progress').value=pct;$('progress-value').textContent=`${pct}%`;$('progress-bytes').textContent=`${fmt(loaded)} / ${fmt(total)}`}
function hideProgress(){setTimeout(()=>$('progress-card').hidden=true,900)}
async function api(path,options={}){options.headers={...(options.headers||{}),...(token?{'X-TinyPhone-Token':token}:{})};const response=await fetch(path,options);const data=await response.json().catch(()=>({error:`HTTP ${response.status}`}));if(!response.ok)throw new Error(language==='vi'?`${t('operationFailed')} (HTTP ${response.status})`:data.error||`HTTP ${response.status}`);return data}
async function refresh(){try{const status=await api('/api/status');token=status.token||token;applyLanguage(status.language);$('connection').textContent=t('connected');$('connection').classList.add('online');$('firmware').textContent=status.firmware;$('sd-state').textContent=status.sdMounted?t('mounted'):t('missing');$('free-space').textContent=fmt(status.freeBytes);$('transfer-state').textContent=t(`state_${status.state}`);$('changes').textContent=status.changes?t('changes',{count:String(status.changes)}):t('noChanges');const media=await api('/api/media');renderMedia(media)}catch(error){$('connection').textContent=t('standalone');$('connection').classList.remove('online');$('notice').textContent=t('unavailable',{error:error.message})}}
function renderMedia(media){const slots=$('wallpaper-slot');const selected=slots.value;slots.replaceChildren(...media.wallpapers.map(w=>new Option(`${t('slot')} ${w.slot}: ${w.name}`,w.slot)));if(selected)slots.value=selected;$('wallpaper-list').replaceChildren(...media.wallpapers.map(w=>{const li=document.createElement('li'),span=document.createElement('span');span.innerHTML=`${t('slot')} ${w.slot}: ${w.name} <small>${w.present?fmt(w.size):t('missing')}</small>`;li.append(span);if(w.present){const button=document.createElement('button');button.className='danger';button.textContent=t('delete');button.onclick=()=>deleteWallpaper(w.slot,w.name);li.append(button)}return li}));$('music-list').replaceChildren(...media.music.map(track=>{const li=document.createElement('li'),span=document.createElement('span'),button=document.createElement('button');span.innerHTML=`${track.name} <small>${fmt(track.size)}</small>`;button.className='danger';button.textContent=t('delete');button.onclick=()=>deleteTrack(track.name);li.append(span,button);return li}))}
function crc32Update(crc,bytes){for(const value of bytes){crc^=value;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return crc>>>0}
async function crc32File(file){let crc=0xffffffff;const chunkSize=1024*1024;for(let offset=0;offset<file.size;offset+=chunkSize){const bytes=new Uint8Array(await file.slice(offset,Math.min(file.size,offset+chunkSize)).arrayBuffer());crc=crc32Update(crc,bytes);showProgress(`${t('checking')} ${file.name}`,Math.min(file.size,offset+bytes.length),file.size)}return(crc^0xffffffff)>>>0}
async function upload(path,file,replace=false){if(busy)return;setBusy(true);try{const crc=(await crc32File(file)).toString(16).padStart(8,'0');await new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',path);xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.setRequestHeader('X-TinyPhone-Token',token);xhr.setRequestHeader('X-Content-CRC32',crc);if(replace)xhr.setRequestHeader('X-TinyPhone-Replace','true');xhr.upload.onprogress=e=>showProgress(file.name,e.loaded,e.total);xhr.upload.onload=()=>{$('progress-name').textContent=t('state_applying');$('progress').value=95;$('progress-value').textContent='95%'};xhr.onload=()=>{let data={};try{data=JSON.parse(xhr.responseText)}catch{}xhr.status>=200&&xhr.status<300?resolve(data):reject(new Error(language==='vi'?`${t('operationFailed')} (HTTP ${xhr.status})`:data.error||`HTTP ${xhr.status}`))};xhr.onerror=()=>reject(new Error(t('networkError')));xhr.send(file)});showProgress(file.name,file.size,file.size,true);await refresh();hideProgress()}finally{setBusy(false)}}
$('package-upload').onclick=async()=>{const file=$('package-file').files[0];if(!file)return alert(t('choosePackage'));if(!/\.tar$/i.test(file.name))return alert(t('chooseStudioPackage'));try{await upload('/api/package',file)}catch(e){alert(e.message)}};
$('wallpaper-upload').onclick=async()=>{const file=$('wallpaper-file').files[0];if(!file)return alert(t('chooseBin'));if(file.size!==153612)return alert(t('wallpaperSize'));try{await upload(`/api/wallpapers/${$('wallpaper-slot').value}`,file,true)}catch(e){alert(e.message)}};
$('music-file').onchange=()=>{const file=$('music-file').files[0];if(file&&!$('music-name').value)$('music-name').value=file.name.toLowerCase().replace(/[^a-z0-9_.]+/g,'_')};
$('music-upload').onclick=async()=>{const file=$('music-file').files[0],name=$('music-name').value;if(!file)return alert(t('chooseWav'));if(!/^[a-z0-9][a-z0-9_]*\.wav$/.test(name))return alert(t('safeName'));try{await upload(`/api/music/${name}`,file,$('music-replace').checked)}catch(e){alert(e.message)}};
$('playlist-upload').onclick=async()=>{const file=$('playlist-file').files[0];if(!file)return alert(t('choosePlaylist'));try{await upload('/api/playlist',file,true)}catch(e){alert(e.message)}};
async function deleteTrack(name){if(busy||!confirm(t('deleteConfirm',{name})))return;setBusy(true);try{await api(`/api/music/${name}`,{method:'DELETE',headers:{'X-TinyPhone-Confirm':name}});await refresh()}catch(e){alert(e.message)}finally{setBusy(false)}}
async function deleteWallpaper(slot,name){if(busy||!confirm(t('deleteConfirm',{name})))return;setBusy(true);try{await api(`/api/wallpapers/${slot}`,{method:'DELETE',headers:{'X-TinyPhone-Confirm':String(slot)}});await refresh()}catch(e){alert(e.message)}finally{setBusy(false)}}
$('apply').onclick=async()=>{if(!confirm(t('applyConfirm')))return;setBusy(true);try{await api('/api/apply',{method:'POST'});$('notice').textContent=t('restartNotice')}catch(e){alert(e.message);setBusy(false)}};
$('exit').onclick=async()=>{if(!confirm(t('exitConfirm')))return;setBusy(true);try{await api('/api/exit',{method:'POST'});$('notice').textContent=t('closingNotice')}catch(e){alert(e.message);setBusy(false)}};
applyLanguage('en');
refresh();setInterval(()=>{if(!busy)refresh()},5000);
